class PuzzleBlock {
      final int id;
      int x;
      int y;
      final int length;
      final bool isHorizontal;
      final bool isTarget;
      double logicalX;
      double logicalY;
      
      PuzzleBlock({
        required this.id, required this.x, required this.y,
        required this.length, required this.isHorizontal, this.isTarget = false,
      }) : logicalX = x.toDouble(), logicalY = y.toDouble();
      PuzzleBlock copy() => PuzzleBlock(id: id, x: x, y: y, length: length, isHorizontal: isHorizontal, isTarget: isTarget);
    }
    class KeyEscapeLevels {
      static int getTargetMoves(int index) {
        List<int> targets = [28, 34, 31, 37, 29, 36, 26, 28, 33, 38, 30, 27, 30, 31, 28, 30, 27, 33, 29, 28, 41, 25, 29, 34, 30, 28, 26, 29, 33, 37, 30, 33, 27, 25, 27, 29, 27, 29, 40, 30, 30, 28, 26, 25, 25, 29, 27, 28, 27, 28, 29, 32, 26, 45, 25, 36, 27, 28, 26, 35, 25, 29, 25, 29, 32, 31, 25, 40, 27, 25, 26, 33, 34, 25, 31, 29, 43, 28, 29, 26, 27, 39, 29, 33, 36, 25, 33, 34, 26, 37];
        return targets[index % targets.length];
      }
      static List<PuzzleBlock> getLevel(int index) {
        List<List<PuzzleBlock>> levels = [
      // Level 1 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 2 (Min Moves: 34)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 3 (Min Moves: 31)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 4 (Min Moves: 37)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 5 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 6 (Min Moves: 36)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 7 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 8 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 9 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 10 (Min Moves: 38)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 11 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 12 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 13 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 12, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 14 (Min Moves: 31)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 15 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 1, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 16 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 17 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 18 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 19 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 20 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 21 (Min Moves: 41)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 22 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 23 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 24 (Min Moves: 34)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 25 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 12, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 26 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 27 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 28 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 29 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 30 (Min Moves: 37)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 31 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 32 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 33 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 34 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 35 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 36 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 37 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 38 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 39 (Min Moves: 40)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 40 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 41 (Min Moves: 30)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 42 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 43 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 44 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 45 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 46 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 47 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 48 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 49 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 50 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 12, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 51 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 52 (Min Moves: 32)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 53 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 54 (Min Moves: 45)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 4, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 55 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 1, y: 4, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 56 (Min Moves: 36)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 57 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 58 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 59 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 60 (Min Moves: 35)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 61 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 4, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 62 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 63 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 64 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 65 (Min Moves: 32)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 66 (Min Moves: 31)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 67 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 68 (Min Moves: 40)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 69 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 70 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 71 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 72 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 5, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
      ],
      // Level 73 (Min Moves: 34)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 74 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 75 (Min Moves: 31)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 76 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 77 (Min Moves: 43)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 78 (Min Moves: 28)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 0, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 79 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 12, x: 3, y: 1, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 80 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 81 (Min Moves: 27)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 12, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 82 (Min Moves: 39)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 83 (Min Moves: 29)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 3, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 5, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 0, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 5, y: 0, length: 2, isHorizontal: false, isTarget: false),
      ],
      // Level 84 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 2, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 10, x: 3, y: 3, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 85 (Min Moves: 36)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 1, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 0, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 3, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 2, y: 3, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 86 (Min Moves: 25)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 4, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 4, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 0, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 87 (Min Moves: 33)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 2, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 3, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 1, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 4, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 4, y: 4, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
      ],
      // Level 88 (Min Moves: 34)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 0, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 3, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 5, y: 0, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 5, x: 1, y: 5, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 2, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 4, y: 3, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 0, y: 1, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 89 (Min Moves: 26)
      [
        PuzzleBlock(id: 0, x: 1, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 5, y: 1, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 2, x: 2, y: 4, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 3, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 1, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 1, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 6, x: 4, y: 2, length: 3, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 3, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 8, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
      ],
      // Level 90 (Min Moves: 37)
      [
        PuzzleBlock(id: 0, x: 0, y: 2, length: 2, isHorizontal: true, isTarget: true),
        PuzzleBlock(id: 1, x: 0, y: 4, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 2, x: 1, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 3, x: 5, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 4, x: 1, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 5, x: 3, y: 5, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 6, x: 2, y: 1, length: 3, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 7, x: 0, y: 0, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 8, x: 2, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 9, x: 4, y: 0, length: 2, isHorizontal: true, isTarget: false),
        PuzzleBlock(id: 10, x: 4, y: 2, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 11, x: 3, y: 3, length: 2, isHorizontal: false, isTarget: false),
        PuzzleBlock(id: 12, x: 5, y: 1, length: 2, isHorizontal: false, isTarget: false),
      ],
        ];
        return levels[index % levels.length].map((b) => b.copy()).toList();
      }
    }